config/routes.rb
Rails.application.routes.draw do

  resource :login
  resources :users
  resources :messages do
    resources :comments, only:[:create, :destroy]

  end

  root 'messages#index'

end

app/models/branch.rb
class Branch < ActiveRecord::Base
  has_many :users
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :message
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

app/models/position.rb
class Position < ActiveRecord::Base
  has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :branch
  belongs_to :position
  has_many :messages
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end

  helper_method :current_user

  private

  def authenticate
    redirect_to login_path unless session[:user_id]
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @message = Message.find(params[:message_id])
    @comment = @message.comments.build(comment_params)
    @comment.user_id = session[:user_id]
    @comment.save
    redirect_to :root
  end

  private

  def comment_params
    params[:comment].permit(:text)
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController

  skip_filter :authenticate

  def show
    render "new", :layout => false
  end

  def create
    if User.exists?(:login_id => params[:login_id], :password => params[:password])
      user = User.find_by(:login_id => params[:login_id])
      session[:user_id] = user.id
      redirect_to :root
    else
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    @current_user = nil
    redirect_to :root
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    @messages = Message.all
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    @message.user_id = session[:user_id]
    if @message.save
      redirect_to messages_path
    else
      render 'new'
    end

  end

  private

    def message_params
      params[:message].permit(:subject, :text, :category)
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    @position = Position.new
    @branch = Branch.new
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to users_path
  end

  private

    def user_params
      params[:user].permit(:login_id, :password, :name, :branch_id, :position_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BBS</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= link_to image_tag("wattaina-top.png"), :root %><br>
<% if current_user == nil %>
  ・<%= link_to "ログイン", login_path %>
<% else %>
  ・<%= link_to 'ログアウト', login_path, :method => :delete %>
<% end %>
・<%= link_to '管理', users_path %>
・<%= link_to '新規投稿', new_message_path %>
・<%= link_to "新規登録", new_user_path %>
　ようこそ！<%= current_user.name %>さん
<%= yield %>

</body>
</html>

app/views/logins/new.html.erb
<h1>ログイン</h1>

<%= form_tag login_path do %>

<p>
  <%= label_tag :login_id %><br>
  <%= text_field_tag :login_id, params[:login_id] %>
</p>

<p>
  <%= label_tag :password %><br>
  <%= password_field_tag :password, params[:password] %>
</p>

<p>
  <%= submit_tag %>
</p>

<% end %>

app/views/messages/index.html.erb
<h1>投稿一覧</h1>

<%= @user %>
<table>
  <% @messages.each do |message| %>
  <tr>
    <td>
      <% message_user = User.find(message.user_id) %>
      投稿者：<%= message_user.name %>
      カテゴリー：<%= message.category %>
    </td>
  </tr>
  <tr>
    <td>件名：<%= message.subject%></td>
  </tr>
  <tr>
    <td>本文<pre><%= message.text %></pre></td>
  </tr>
  <tr>
    <td>----------コメント----------</td>
  </tr>
  <% message.comments.each do |comment| %>
  <tr>
    <td>
      <% comment_user = User.find(comment.user_id) %>
      名前:<%= comment_user.name %>
    </td>
  </tr>
  <tr>
    <td>本文<pre><%= comment.text %></pre></td>
  </tr>
  <% end %>
  <%= form_for [message, message.comments.build] do |f| %>
  <tr>
    <td><%= f.text_area :text %></td>
  </tr>
  <tr>
    <td><%= f.submit 'コメント' %></td>
  </td>
  <% end %>
  <% end %>
</table>

app/views/messages/new.html.erb
<h1>新規投稿</h1>

<%= form_for @message do |f| %>

<p>
  <%= f.label :subject %><br>
  <%= f.text_field :subject %>
</p>

<p>
  <%= f.label :text %><br>
  <%= f.text_area :text %>
</p>

<p>
  <%= f.label :category %>
  <%= f.text_field :category %>
</p>

<p>
  <%= f.submit %>
</p>

<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

<p>
  <%= f.label :login_id %><br>
  <%= f.text_field :login_id %>
</p>

<p>
  <%= f.label :password %><br>
  <%= f.password_field :password %>
</p>

<p>
  <%= f.label :name %><br>
  <%= f.text_field :name %>
</p>

<p>
  <%= f.label :branch_id %><br>
  <%= f.select :branch_id,  Branch.all.map{|branch| [branch.name, branch.id]} %>
</p>

<p>
  <%= f.label :position_id %><br>
  <%= f.select :position_id,  Position.all.map{|position| [position.name, position.id] } %></p>

<p>
  <%= f.submit %>
</p>

<% end %>

app/views/users/edit.html.erb
<h1>編集</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>社員一覧</h1>

<table>
  <tr>
    <th>Name</th>
    <th>ID</th>
    <th>Company</th>
    <th>Department</th>
    <th>Log in</th>
  <tr/>
  <% @users.each do |user| %>
  <tbody class="target">
    <tr>
      <td><%= link_to user.name, edit_user_path(user.id) %></td>
      <td><%= user.login_id %></td>
      <% branch = Branch.find_by id: user.branch_id %>
      <td><%= branch.name %></td>
      <% position = Position.find_by id: user.position_id %>
      <td><%= position.name %></td>
      <% if user.stopped %>
        <th><%= button_tag 'ON', {:calss => 'stop', 'data-id' => user.id, 'data-stopped' => user.stopped} %></th>
      <% else %>
        <th><%= button_tag 'OFF', {:calss => 'stop', 'data-stopped' => user.stopped} %></th>
      <% end %>
    </tr>
  </tbody>
  <% end %>
</table>

<script>
$(function() {
  $("[type=submit]").click(function() {
    alert('Click');
  })
})
</script>

app/views/users/new.html.erb
<h1>新規登録</h1>

<%= render 'form' %>